name: "Close Stale Issues and PRs"
description: "Automatically closes issues and pull requests that have been stale for a specified time."
inputs:
  days-before-stale:
    description: "Days before an issue or PR is considered stale"
    required: false
    default: "80"
  days-before-close:
    description: "Days before a stale issue or PR is closed"
    required: false
    default: "12"
runs:
  using: "composite"
  steps:
    - name: Close Stale Issues
      uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: ${{ inputs.days-before-stale || '90' }} # Use default if not provided
        days-before-close: ${{ inputs.days-before-close || '14' }} # Use default if not provided
        stale-issue-message: "This issue has been marked as stale due to inactivity."
        close-issue-message: "Closing this issue due to prolonged inactivity."
