name: "Pull Latest Submodule Update"
description: "Workflow to pull latest submodule update"
inputs:
  token:
    required: true
    description: "GitHub token for authentication"
  git_user_email:
    required: false
    description: "Git user email"
  git_user_name:
    required: false
    description: "Git user name"
  issue_id:
    required: false
    description: "Issue or PR ID to update"
runs:
  using: "composite"
  steps:
    - name: Checkout target repository with submodules
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}
        submodules: true
        fetch-depth: 0

    - name: Get PR Branch
      id: get_pr_branch
      run: |
        if [ -n "${{ inputs.issue_id }}" ]; then
          PR_INFO=$(curl -s -H "Authorization: token ${{ inputs.token }}" "https://api.github.com/repos/${{ github.repository }}/pulls/${{ inputs.issue_id }}")
          BRANCH_NAME=$(echo $PR_INFO | jq -r .head.ref)
        else
          echo "No PR number provided."
          BRANCH_NAME="submodule-update-$(date +%Y%m%d%H%M%S)"
        fi
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
      shell: bash

    - name: Update Shared Actions
      id: update_shared_actions
      run: |
        git config --global user.email "${{ inputs.git_user_email }}"
        git config --global user.name "${{ inputs.git_user_name }}" 
        git submodule update --remote --checkout
      shell: bash

    - name: Create Pull Request
      id: create_pr
      if: ${{ inputs.issue_id == '' }}
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.token }}
        committer: "${{ inputs.git_user_name }} <${{ inputs.git_user_email }}>"
        branch: ${{ env.BRANCH_NAME }}
        title: "Update shared actions submodule"
        commit-message: "Update to latest shared actions submodule"
        author: "${{ inputs.git_user_name }} <${{ inputs.git_user_email }}>"
        labels: |
          update-modules
        body: "This PR updates the shared actions submodule to the latest commit."
        delete-branch: true
        draft: false

    - name: Push Changes
      if: ${{ inputs.issue_id != '' }}
      run: |
        git checkout $BRANCH_NAME
        git add .github/actions/shared-actions
        git commit -m "Update to latest shared actions submodule" || echo "No changes to commit"
        git push origin $BRANCH_NAME
      shell: bash