name: Close Stale Issues and PRs

on:
  workflow_call:
    secrets:
      token:
        required: true
      GIT_USER_EMAIL:
        required: true
      GIT_USER_NAME:
        required: true
    inputs:
      days-before-stale:
        description: "Days before an issue or PR is considered stale"
        required: false
        default: "90"
        type: string
      days-before-close:
        description: "Days before a stale issue or PR is closed"
        required: false
        default: "14"
        type: string
jobs:
  close_stale:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git User
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"

      - name: Close Stale Issues
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.token }}
          days-before-stale: ${{ inputs.days-before-stale }}
          days-before-close: ${{ inputs.days-before-close }}
          stale-issue-message: "This issue has been marked as stale due to inactivity."
          close-issue-message: "Closing this issue due to prolonged inactivity."
