name: Close Stale Issues and PRs

on:
  workflow_call:
    inputs:
      days-before-stale:
        description: "Days before an issue or PR is considered stale"
        required: false
        default: "90"
        type: string
      days-before-close:
        description: "Days before a stale issue or PR is closed"
        required: false
        default: "14"
        type: string
      token:
        description: "Personal Access Token (PAT) for the bot. Uses GITHUB_TOKEN if not provided."
        required: false
        type: string
      git_user_email:
        description: "Email address of the bot. Only used if provided."
        required: false
        type: string
      git_user_name:
        description: "Username of the bot. Only used if provided."
        required: false
        type: string

jobs:
  close_stale:
    runs-on: ubuntu-latest

    steps:
      - name: Close Stale Issues
        uses: actions/stale@v9
        with:
          repo-token: ${{ inputs.token || secrets.BOT_TOKEN }}
          days-before-stale: ${{ inputs.days-before-stale }}
          days-before-close: ${{ inputs.days-before-close }}
          stale-issue-message: "This issue has been marked as stale due to inactivity."
          close-issue-message: "Closing this issue due to prolonged inactivity."
